[tool.poetry]
name = "canvas-course-tools"
version = "0.1.0"
description = "Canvas course tools"
authors = ["David Fokkema <d.b.r.a.fokkema@vu.nl>"]

[tool.poetry.scripts]
canvas = "canvas_course_tools.cli:cli"

[tool.poetry.dependencies]
python = "^3.9"
click = "^7.1.2"
appdirs = "^1.4.4"
toml = "^0.10.2"
rich = "^10.1.0"
canvasapi = "^2.2.0"
python-dateutil = "^2.8.1"
rich-click = "^1.5.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
ipython = "^7.22.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
